apiVersion: v1
kind: Service
metadata:
  name: client-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - name: http
      port: 31000       #是指暴露在cluster ip上的端口 必填
      targetPort: 31000 #是指pod上的端口
      nodePort: 31000   #指定k8s的node暴露的端口 30000-32767