apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service
  name: service-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      nodeName: local3
      containers:
        - image: sealos.hub:5000/chuan/service
          imagePullPolicy: IfNotPresent
          name: service
          ports:
            - name: http
              containerPort: 32000
              protocol: TCP
