apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: service
  ports:
    - name: http
      port: 32000       #是指暴露在cluster ip上的端口 必填
      targetPort: 32000 #是指pod上的端口
      nodePort: 32000  #指定k8s的node暴露的端口 30000-32767