apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      nodeName: local2
      containers:
        - image: sealos.hub:5000/chuan/client
          imagePullPolicy: IfNotPresent
          name: client
          ports:
            - name: http
              containerPort: 31000
              protocol: TCP
